export default {
  44: 'ChunkVersion> A byte',
  45: 'Data2D> Biomes and elevation',
  46: 'Data2DLegacy',
  47: 'SubChunkPrefix> Terrain for a 16×16×16 subchunk',
  48: 'LegacyTerrain> Terrain for an entire chunk',
  49: 'BlockEntity> Block entity data (little-endian NBT)',
  50: 'Entity> Entity data (little-endian NBT)',
  51: 'PendingTicks> Pending tick data (little-endian NBT)',
  52: 'BlockExtraData> No longer Used',
  53: 'BiomeState',
  54: 'FinalizedState> A 32-bit little endian integer',
  55: 'No longer used',
  56: 'BorderBlocks> Education Edition Feature',
  57: 'HardCodedSpawnAreas> Bounding boxes for structure spawns stored in binary format',
  58: 'RandomTicks> Random tick data (little-endian NBT)',
  59: 'Checksums> xxHash checksums of other chunk records',
  118: 'ChunkVersion> A byte. Moved to 44 in v1.16.100',
};
